# Generated by Django 3.0.6 on 2020-05-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Theatrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=1023)),
                ('time', models.DateTimeField()),
                ('duration', models.ImageField(upload_to='')),
                ('tickets_url', models.URLField()),
                ('poster_url', models.URLField()),
                ('genre', models.ManyToManyField(to='playbil.Genre')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbil.Theater')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbil.Type')),
                ('worker', models.ManyToManyField(to='playbil.Worker')),
            ],
        ),
    ]
