# Generated by Django 3.0.6 on 2020-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='photo_url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
