# Generated by Django 3.0.6 on 2020-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0002_theater_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
