# Generated by Django 3.0.6 on 2020-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0003_theater_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='description',
            field=models.TextField(default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='theater',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='theater',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theater',
            name='schedule',
            field=models.CharField(default='', max_length=255),
        ),
    ]
