# Generated by Django 3.0.6 on 2020-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0004_auto_20200511_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
