# Generated by Django 3.0.6 on 2020-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0006_auto_20200511_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
