# Generated by Django 3.0.3 on 2020-05-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbil', '0011_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
